/* tslint:disable */
/* eslint-disable */
/**
 * NeatPallet application
 * Proyecto API encargado de ser la parte Backend de la aplicación web NEATPALLET
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: agusjar@hotmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

